### PR TITLE
Added bootstrap theme and moved some helpers around.

### PR DESCRIPTION
**Pull request by jf26028**
Added bootstrap theme and moved some helpers to allow for custom themes without having to modify the core.
- Did not modify the standard theme functionality.
- Moved helpers from the Helpers.cshtml page to the individual themes.  This caused some slight "mostly" duplicate code, but separated the concern for each theme, which is required.
- Added a new theme that is based on vanilla bootstrap for demonstration purposes.
- Added gulp tasks to build both themes.  I didn't like how this turned out, but seemed like the best way to go about it.

This PR does not really enhance your site, other than show a clear and simple path for adding additional themes without having to modify any core code.  Please don't hesitate to reject this PR.

And, thanks for your work on this.  The simplicity is inspiring.

### CODE REVIEW

**Comment by jf26028** [comment]
The build fails because of the node_modules folder.  A bit of a pain with webpages.  I prefer the webcompiler and bundler and minifier plugins, but I didn't want to get too far off the rails with this PR.

**Comment by madskristensen** [comment]
Thanks for the PR. I do always appreciate getting PRs, but this one unfortunately falls outside of the direction I was taking with this project

**Comment by jf26028** [comment]
Sounds good.  I can respect that.  It really doesn't add a lot of value to what you are currently shooting for.

I do love this project, though.  Do you have any plans or direction where you are headed?  

In any case, thanks for taking the time to review and respond.

**Comment by madskristensen** [comment]
The work has continued over here https://github.com/aspnet/vsweb-docs

**Pull request closed without merging**
